/bin/sh: line 1: /root/sync_test/sync_git.sh: No such file or directory
/bin/sh: line 1: /root/sync_test/sync_git.sh: No such file or directory
/bin/sh: line 1: /root/sync_test/sync_git.sh: No such file or directory
/bin/sh: line 1: /root/sync_test/sync_git.sh: No such file or directory
/bin/sh: line 1: /root/sync_test/sync_git.sh: No such file or directory
/bin/sh: line 1: /root/sync_test/sync_git.sh: No such file or directory
/bin/sh: line 1: /root/sync_test/sync_git.sh: No such file or directory
/bin/sh: line 1: /root/sync_test/sync_git.sh: No such file or directory
/bin/sh: line 1: /root/sync_test/sync_git.sh: No such file or directory
fatal: unable to access 'https://github.com/cdac3642/sync_test.git/': Could not resolve host: github.com
[main f6c6c2c] Automated commit
 3 files changed, 13 insertions(+), 1 deletion(-)
 create mode 100644 hello
 create mode 100644 sync_log.txt
fatal: unable to access 'https://github.com/cdac3642/sync_test.git/': Could not resolve host: github.com
fatal: unable to access 'https://github.com/cdac3642/sync_test.git/': Could not resolve host: github.com
[main 49961da] Automated commit
 1 file changed, 6 insertions(+)
To https://github.com/cdac3642/sync_test.git
   4739d1f..49961da  main -> main
fatal: unable to access 'https://github.com/cdac3642/sync_test.git/': Could not resolve host: github.com
[main 445082e] Automated commit
 1 file changed, 5 insertions(+)
To https://github.com/cdac3642/sync_test.git
   49961da..445082e  main -> main
fatal: unable to access 'https://github.com/cdac3642/sync_test.git/': Could not resolve host: github.com
[main 5c1f0ad] Automated commit
 1 file changed, 5 insertions(+)
fatal: unable to access 'https://github.com/cdac3642/sync_test.git/': Could not resolve host: github.com
Already up to date.
[main 8ebcdf4] Automated commit
 2 files changed, 5 insertions(+)
 create mode 100644 assignment
To https://github.com/cdac3642/sync_test.git
   445082e..8ebcdf4  main -> main
Already up to date.
[main 3a6f651] Automated commit
 1 file changed, 6 insertions(+)
To https://github.com/cdac3642/sync_test.git
   8ebcdf4..3a6f651  main -> main
Already up to date.
[main cb5b3f2] Automated commit
 1 file changed, 5 insertions(+)
To https://github.com/cdac3642/sync_test.git
   3a6f651..cb5b3f2  main -> main
Already up to date.
[main 9545b34] Automated commit
 1 file changed, 5 insertions(+)
To https://github.com/cdac3642/sync_test.git
   cb5b3f2..9545b34  main -> main
fatal: unable to access 'https://github.com/cdac3642/sync_test.git/': Could not resolve host: github.com
[main 222c17f] Automated commit
 1 file changed, 5 insertions(+)
To https://github.com/cdac3642/sync_test.git
   9545b34..222c17f  main -> main
Already up to date.
[main ca47751] Automated commit
 1 file changed, 5 insertions(+)
To https://github.com/cdac3642/sync_test.git
   222c17f..ca47751  main -> main
fatal: unable to access 'https://github.com/cdac3642/sync_test.git/': Could not resolve host: github.com
[main 832b6b5] Automated commit
 1 file changed, 5 insertions(+)
To https://github.com/cdac3642/sync_test.git
   ca47751..832b6b5  main -> main
Already up to date.
[main e72944f] Automated commit
 1 file changed, 5 insertions(+)
fatal: unable to access 'https://github.com/cdac3642/sync_test.git/': Could not resolve host: github.com
Already up to date.
[main 50cb0b8] Automated commit
 1 file changed, 4 insertions(+)
To https://github.com/cdac3642/sync_test.git
   832b6b5..50cb0b8  main -> main
fatal: unable to access 'https://github.com/cdac3642/sync_test.git/': Could not resolve host: github.com
[main f13c7a7] Automated commit
 1 file changed, 5 insertions(+)
To https://github.com/cdac3642/sync_test.git
   50cb0b8..f13c7a7  main -> main
Already up to date.
[main b023734] Automated commit
 1 file changed, 5 insertions(+)
To https://github.com/cdac3642/sync_test.git
   f13c7a7..b023734  main -> main
fatal: unable to access 'https://github.com/cdac3642/sync_test.git/': Could not resolve host: github.com
[main 70e7102] Automated commit
 1 file changed, 5 insertions(+)
fatal: unable to access 'https://github.com/cdac3642/sync_test.git/': Could not resolve host: github.com
fatal: unable to access 'https://github.com/cdac3642/sync_test.git/': Could not resolve host: github.com
[main 9c4a4d9] Automated commit
 1 file changed, 4 insertions(+)
fatal: unable to access 'https://github.com/cdac3642/sync_test.git/': Could not resolve host: github.com
fatal: unable to access 'https://github.com/cdac3642/sync_test.git/': Could not resolve host: github.com
[main caab437] Automated commit
 1 file changed, 4 insertions(+)
fatal: unable to access 'https://github.com/cdac3642/sync_test.git/': Could not resolve host: github.com
Already up to date.
[main acf3991] Automated commit
 1 file changed, 4 insertions(+)
To https://github.com/cdac3642/sync_test.git
   b023734..acf3991  main -> main
fatal: unable to access 'https://github.com/cdac3642/sync_test.git/': Could not resolve host: github.com
