/bin/sh: line 1: /root/sync_test/sync_git.sh: No such file or directory
/bin/sh: line 1: /root/sync_test/sync_git.sh: No such file or directory
/bin/sh: line 1: /root/sync_test/sync_git.sh: No such file or directory
/bin/sh: line 1: /root/sync_test/sync_git.sh: No such file or directory
/bin/sh: line 1: /root/sync_test/sync_git.sh: No such file or directory
/bin/sh: line 1: /root/sync_test/sync_git.sh: No such file or directory
/bin/sh: line 1: /root/sync_test/sync_git.sh: No such file or directory
/bin/sh: line 1: /root/sync_test/sync_git.sh: No such file or directory
/bin/sh: line 1: /root/sync_test/sync_git.sh: No such file or directory
fatal: unable to access 'https://github.com/cdac3642/sync_test.git/': Could not resolve host: github.com
[main f6c6c2c] Automated commit
 3 files changed, 13 insertions(+), 1 deletion(-)
 create mode 100644 hello
 create mode 100644 sync_log.txt
fatal: unable to access 'https://github.com/cdac3642/sync_test.git/': Could not resolve host: github.com
fatal: unable to access 'https://github.com/cdac3642/sync_test.git/': Could not resolve host: github.com
[main 49961da] Automated commit
 1 file changed, 6 insertions(+)
To https://github.com/cdac3642/sync_test.git
   4739d1f..49961da  main -> main
fatal: unable to access 'https://github.com/cdac3642/sync_test.git/': Could not resolve host: github.com
[main 445082e] Automated commit
 1 file changed, 5 insertions(+)
To https://github.com/cdac3642/sync_test.git
   49961da..445082e  main -> main
fatal: unable to access 'https://github.com/cdac3642/sync_test.git/': Could not resolve host: github.com
[main 5c1f0ad] Automated commit
 1 file changed, 5 insertions(+)
fatal: unable to access 'https://github.com/cdac3642/sync_test.git/': Could not resolve host: github.com
Already up to date.
[main 8ebcdf4] Automated commit
 2 files changed, 5 insertions(+)
 create mode 100644 assignment
To https://github.com/cdac3642/sync_test.git
   445082e..8ebcdf4  main -> main
Already up to date.
[main 3a6f651] Automated commit
 1 file changed, 6 insertions(+)
To https://github.com/cdac3642/sync_test.git
   8ebcdf4..3a6f651  main -> main
Already up to date.
[main cb5b3f2] Automated commit
 1 file changed, 5 insertions(+)
To https://github.com/cdac3642/sync_test.git
   3a6f651..cb5b3f2  main -> main
Already up to date.
[main 9545b34] Automated commit
 1 file changed, 5 insertions(+)
To https://github.com/cdac3642/sync_test.git
   cb5b3f2..9545b34  main -> main
fatal: unable to access 'https://github.com/cdac3642/sync_test.git/': Could not resolve host: github.com
[main 222c17f] Automated commit
 1 file changed, 5 insertions(+)
To https://github.com/cdac3642/sync_test.git
   9545b34..222c17f  main -> main
Already up to date.
